# Generated by Django 2.2.10 on 2020-03-03 14:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='', upload_to=users.models.agent_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fullname',
            field=models.CharField(max_length=200, verbose_name='fullname'),
        ),
    ]
