# Generated by Django 2.2.10 on 2020-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200401_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_account_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='account manager'),
        ),
    ]
