# Generated by Django 2.2.10 on 2020-04-03 13:21

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone]),
        ),
    ]
