# Generated by Django 2.2.10 on 2020-07-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='has_air_condititoning',
            new_name='has_air_conditioning',
        ),
    ]
