# Generated by Django 2.2.10 on 2020-07-08 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200707_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
