# Generated by Django 2.2.10 on 2020-07-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_bookmarkedhotel_hotelbookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelphotos',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelPhotos', to='hotels.Hotel'),
        ),
    ]
