# Generated by Django 2.2.10 on 2020-09-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200504_1251'),
        ('hotels', '0010_auto_20200714_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lga',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_lga', to='properties.LGA'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_state', to='properties.State'),
        ),
        migrations.AlterField(
            model_name='bookmarkedhotel',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarkedHotel', to='hotels.Hotel'),
        ),
        migrations.AlterField(
            model_name='bookmarkedhotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarkedHotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
