# Generated by Django 2.2.10 on 2020-10-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_auto_20200929_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_state', to='properties.State'),
        ),
    ]
