# Generated by Django 2.2.10 on 2020-04-20 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import properties.models
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False, help_text='click here to approve or disapprove this company', verbose_name='approve company')),
                ('is_featured', models.BooleanField(default=False, help_text='click here if this company made payment to be featured', verbose_name='feature company')),
                ('is_featured_expires', models.DateField(blank=True, null=True, verbose_name='feature expiry date')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='company name')),
                ('office_phone', models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone])),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone])),
                ('address', models.CharField(max_length=200, null=True, verbose_name='address')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to=properties.models.company_logo_image_path, verbose_name='logo')),
                ('account_type', models.CharField(choices=[('agent', 'agent'), ('developer', 'developer')], default='agent', max_length=20, verbose_name='account type')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(default=django.utils.crypto.get_random_string, max_length=40, unique=True, verbose_name='Property ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=400, verbose_name='slug')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='area')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='zipcode or postal code')),
                ('property_category', models.CharField(choices=[('sale', 'sale'), ('rent', 'rent'), ('lease', 'lease')], default='sale', max_length=20, verbose_name='category')),
                ('property_type', models.CharField(choices=[('all', 'all'), ('flat', 'flat'), ('house', 'house'), ('land', 'land'), ('commercial', 'commercial'), ('event centre', 'event centre')], default='all', max_length=20, verbose_name='type')),
                ('market_status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=20, verbose_name='status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('country', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.Company')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'get_latest_by': ['created'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='state')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('livingrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_area', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('covered_area', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('toilets', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_basketball_court', models.BooleanField(default=False, verbose_name='basketball court')),
                ('has_gym', models.BooleanField(default=False, verbose_name='gym')),
                ('is_wheelchair_friendly', models.BooleanField(default=False, verbose_name='wheelchair friendly')),
                ('has_swimming_pool', models.BooleanField(default=False, verbose_name='swimming pool')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='properties.Property')),
            ],
            options={
                'verbose_name_plural': 'Property Details',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.State'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=properties.models.property_images_directory_path, verbose_name='image')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.Property')),
            ],
            options={
                'verbose_name_plural': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='BookmarkedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked', to='properties.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('unbooked', 'unbooked')], default='unbooked', max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to='properties.Company')),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to='properties.PropertyDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
