# Generated by Django 2.2.10 on 2020-03-03 14:05

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200303_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='country name')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('property_id', models.CharField(max_length=7, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('neighborhood', models.CharField(blank=True, max_length=200, null=True, verbose_name='neighborhood')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='zipcode or postal code')),
                ('property_status', models.CharField(default='rent', max_length=20, verbose_name='status')),
                ('property_type', models.CharField(default='all', max_length=20, verbose_name='type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='property price')),
                ('description', models.TextField(verbose_name='description')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Agent')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='state name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('livingrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baths', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('garages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_basketball_court', models.BooleanField(blank=True, null=True, verbose_name='basketball court')),
                ('has_gym', models.BooleanField(blank=True, null=True, verbose_name='gym')),
                ('is_wheelchair_friendly', models.BooleanField(blank=True, null=True, verbose_name='wheelchair friendly')),
                ('has_swimming_pool', models.BooleanField(blank=True, null=True, verbose_name='swimming pool')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.State'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.property_directory_path, verbose_name='image')),
                ('video_link', models.URLField(max_length=255)),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
    ]
