# Generated by Django 2.2.10 on 2020-03-11 12:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'gallery'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': ['created'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='propertydetails',
            options={'verbose_name_plural': 'Property Details'},
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='click here to approve or disapprove this company', verbose_name='approve company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='click here if this company made payment to be featured', verbose_name='feature company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_featured_expires',
            field=models.DateField(blank=True, null=True, verbose_name='feature expiry date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=properties.models.company_logo_image_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.Property'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.Company'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='3c004a8d', max_length=8, unique=True, verbose_name='Property ID'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='has_basketball_court',
            field=models.BooleanField(default=False, verbose_name='basketball court'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='has_gym',
            field=models.BooleanField(default=False, verbose_name='gym'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='has_swimming_pool',
            field=models.BooleanField(default=False, verbose_name='swimming pool'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='is_wheelchair_friendly',
            field=models.BooleanField(default=False, verbose_name='wheelchair friendly'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='properties.Property'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Country'),
        ),
        migrations.CreateModel(
            name='SocialMediaURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('facebook', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=255)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to='properties.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='favorite_properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='properties.Property'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
