# Generated by Django 2.2.10 on 2020-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': ['created'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='593d4835', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
