# Generated by Django 2.2.10 on 2020-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent'), ('lease', 'lease')], max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('all', 'all'), ('flat', 'flat'), ('house', 'house'), ('land', 'land'), ('commercial', 'commercial'), ('event centre', 'event centre')], max_length=20, verbose_name='type'),
        ),
    ]
