# Generated by Django 2.2.10 on 2020-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200311_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='d5554480', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
