# Generated by Django 2.2.10 on 2020-04-08 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_auto_20200311_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('unbooked', 'unbooked')], default='unbooked', max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookmarkedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='socialmediaurl',
            name='client',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='video_link',
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('4f1baefa-e1ca-4c0c-bee4-253505e92d15'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='SocialMediaURL',
        ),
        migrations.AddField(
            model_name='bookmarkedproperty',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked', to='properties.Property'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to='properties.Company'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='property_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to='properties.PropertyDetails'),
        ),
    ]
