# Generated by Django 2.2.10 on 2020-03-25 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200311_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video_link',
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, verbose_name='title'), max_length=400, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('11047ab0-0bb5-4aa8-8fab-6fa92ac76f5a'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
