# Generated by Django 2.2.10 on 2020-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200309_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'gallery'},
        ),
        migrations.AlterModelOptions(
            name='propertydetails',
            options={'verbose_name_plural': 'Property Details'},
        ),
        migrations.AlterField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='click here to approve or disapprove this company', verbose_name='approve company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='click here if this company made payment to be featured', verbose_name='feature company'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='6c9b4bc7', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
