# Generated by Django 2.2.10 on 2020-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200311_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='992e4a47', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
