# Generated by Django 2.2.10 on 2020-04-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200430_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lga',
            options={'verbose_name': 'LGA', 'verbose_name_plural': 'LGA'},
        ),
    ]
