# Generated by Django 2.2.10 on 2020-03-09 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_auto_20200309_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('facebook', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='34af4540', max_length=8, unique=True, verbose_name='Property ID'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='last name')),
                ('favorite_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
                ('social_media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.SocialMediaURL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
