# Generated by Django 2.2.10 on 2020-03-25 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200325_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('f8108c5e-57ef-4716-a59c-bdd56c8e9ff1'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, verbose_name='slug'),
        ),
    ]
