# Generated by Django 2.2.10 on 2020-04-08 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200408_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('7bfc8409-e4cd-4298-9919-444cb3b55c1f'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
