# Generated by Django 2.2.10 on 2020-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200309_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='ab64444c', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
