# Generated by Django 2.2.10 on 2020-05-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200430_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_state', to='properties.State'),
        ),
    ]
