# Generated by Django 2.2.10 on 2020-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200313_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='b4cc41ab', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
