# Generated by Django 2.2.10 on 2020-04-08 16:19

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200408_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=properties.models.generate_property_id, max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
