# Generated by Django 2.2.10 on 2020-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200311_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='e0674e8c', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
