# Generated by Django 2.2.10 on 2020-04-01 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200401_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('b1cceff7-1f60-457c-8648-bbce2020ea0e'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
