# Generated by Django 2.2.10 on 2020-03-13 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200313_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('a966800d-7103-4ca0-96fc-e061c6b69147'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
