# Generated by Django 2.2.10 on 2020-03-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200309_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_featured_expires',
            field=models.DateField(null=True, verbose_name='feature expiry date'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='6f504b85', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
