# Generated by Django 2.2.10 on 2020-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200408_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='market_status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=20, verbose_name='status'),
        ),
    ]
