# Generated by Django 2.2.10 on 2020-03-22 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200313_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('644d84e3-cd5e-4e3c-90e7-a4f4b9d78afa'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
