# Generated by Django 2.2.10 on 2020-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200311_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='dc954e48', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
