# Generated by Django 2.2.10 on 2020-04-03 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200401_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('25d66361-00c5-43fa-8c26-9a27ac57d89c'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
