# Generated by Django 2.2.10 on 2020-05-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_floorplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorplan',
            old_name='image',
            new_name='floor_image',
        ),
    ]
