# Generated by Django 2.2.10 on 2020-04-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200409_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Country'),
        ),
    ]
