# Generated by Django 2.2.10 on 2020-04-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200410_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.State'),
        ),
    ]
