# Generated by Django 2.2.10 on 2020-04-03 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200403_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('b409e290-ed93-49ea-9ce2-1aab84de666a'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
