# Generated by Django 2.2.10 on 2020-03-09 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200309_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='favorite_properties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='properties.Property'),
        ),
        migrations.AlterField(
            model_name='client',
            name='social_media',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='properties.SocialMediaURL'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.Company'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='9fa442f2', max_length=8, unique=True, verbose_name='Property ID'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_details', to='properties.Property'),
        ),
    ]
