# Generated by Django 2.2.10 on 2020-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200311_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='2da34181', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
