# Generated by Django 2.2.10 on 2020-03-22 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200322_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, verbose_name='title'), max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('fd035296-e67e-4e7a-979f-ea32177e72df'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
