# Generated by Django 2.2.10 on 2020-05-04 09:57

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200503_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': ['created'], 'ordering': ['created'], 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='floor_image',
            field=models.ImageField(blank=True, upload_to=properties.models.property_floorplan_directory_path, verbose_name='image'),
        ),
    ]
