# Generated by Django 2.2.10 on 2020-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200410_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('all', 'all'), ('flat', 'flat'), ('house', 'house'), ('land', 'land'), ('commercial', 'commercial'), ('event centre', 'event centre')], default='all', max_length=20, verbose_name='type'),
        ),
    ]
