# Generated by Django 2.2.10 on 2020-03-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200309_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='4daa41e7', max_length=8, unique=True, verbose_name='Property ID'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='has_basketball_court',
            field=models.BooleanField(default=False, verbose_name='basketball court'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='has_gym',
            field=models.BooleanField(default=False, verbose_name='gym'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='has_swimming_pool',
            field=models.BooleanField(default=False, verbose_name='swimming pool'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='is_wheelchair_friendly',
            field=models.BooleanField(default=False, verbose_name='wheelchair friendly'),
        ),
    ]
