# Generated by Django 2.2.10 on 2020-04-03 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200403_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaurl',
            name='client',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('23009131-7088-431d-8bd9-22e88f93d550'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='SocialMediaURL',
        ),
    ]
