# Generated by Django 2.2.10 on 2020-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20200311_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='b6e8405b', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
