# Generated by Django 2.2.10 on 2020-03-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20200309_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='1ddc4046', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
