# Generated by Django 2.2.10 on 2020-04-03 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20200403_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('0a57bea7-2c96-4509-b1ea-1b61e5235250'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
