# Generated by Django 2.2.10 on 2020-03-24 02:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20200322_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('e3aeed34-5558-4864-9399-1da9e72ca595'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
