# Generated by Django 2.2.10 on 2020-04-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200410_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent'), ('lease', 'lease')], default='sale', max_length=20, verbose_name='category'),
        ),
    ]
