# Generated by Django 2.2.10 on 2020-04-03 13:21

from django.db import migrations, models
import users.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200403_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('9bb8bbe5-3a7d-4222-9398-f97081ec7b27'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
