# Generated by Django 2.2.10 on 2020-03-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200311_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='b61a44be', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
