# Generated by Django 2.2.10 on 2020-03-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200309_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='state',
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='4b274db3', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
