# Generated by Django 2.2.10 on 2020-03-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200309_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='social_media',
        ),
        migrations.AddField(
            model_name='socialmediaurl',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialmedia', to='properties.Client'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='1b5e4a06', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
