# Generated by Django 2.2.10 on 2020-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200410_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='tour_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='tour_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
