# Generated by Django 2.2.10 on 2020-03-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200312_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='34544fbb', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
