# Generated by Django 2.2.10 on 2020-04-04 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0011_auto_20200403_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('ebd99fe5-b2c5-48ea-9055-824c91ac3e98'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to='properties.Company')),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingrequest', to='properties.PropertyDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
