# Generated by Django 2.2.10 on 2020-04-05 18:14

from django.db import migrations, models
import users.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20200404_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[users.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('c2b06988-8d2a-4dd1-8497-7f68efa380f0'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
