# Generated by Django 2.2.10 on 2020-03-09 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20200309_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='803547cb', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
