# Generated by Django 2.2.10 on 2020-04-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20200417_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='tour_date',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='tour_time',
        ),
    ]
