# Generated by Django 2.2.10 on 2020-04-06 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20200405_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('unbooked', 'unbooked')], default='unbooked', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default=uuid.UUID('8ada0f6b-4266-4966-b4c7-87de22848949'), max_length=40, unique=True, verbose_name='Property ID'),
        ),
    ]
