# Generated by Django 2.2.10 on 2020-03-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20200309_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='d5a9438e', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
