# Generated by Django 2.2.10 on 2020-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20200312_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='e12d4858', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
