# Generated by Django 2.2.10 on 2020-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20200417_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_type',
            field=models.CharField(choices=[('agent', 'agent'), ('developer', 'developer')], default='agent', max_length=20, verbose_name='account type'),
        ),
    ]
