# Generated by Django 2.2.10 on 2020-03-09 19:23

import django.core.validators
from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20200309_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_featured_expires',
            field=models.DateField(blank=True, null=True, verbose_name='feature expiry date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=properties.models.company_logo_image_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='office_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='a84741af', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
