# Generated by Django 2.2.10 on 2020-03-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20200309_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='video_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='b30f4c99', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
