# Generated by Django 2.2.10 on 2020-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_auto_20200313_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='877045b0', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
