# Generated by Django 2.2.10 on 2020-03-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20200309_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='e8a44c27', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
