# Generated by Django 2.2.10 on 2020-03-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20200309_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='797c46af', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
