# Generated by Django 2.2.10 on 2020-03-13 10:01

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20200313_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_images_directory_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.CharField(default='d9cb46dc', max_length=8, unique=True, verbose_name='Property ID'),
        ),
    ]
